# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-18 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    )
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255,
                        verbose_name='name',
                    )
                ),
            ],
        ),
        migrations.CreateModel(
            name='PersonPets',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    )
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        default=False,
                        verbose_name='is deleted',
                    )
                ),
                (
                    'person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pet_relations',
                        to='filtered_many_to_many.Person',
                        verbose_name='person',
                    )
                ),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    )
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255,
                        verbose_name='name',
                    )
                ),
            ],
        ),
        migrations.AddField(
            model_name='personpets',
            name='pet',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='person_relations',
                to='filtered_many_to_many.Pet',
                verbose_name='pet',
            ),
        ),
        migrations.AddField(
            model_name='person',
            name='pets',
            field=models.ManyToManyField(
                related_name='people',
                through='filtered_many_to_many.PersonPets',
                to='filtered_many_to_many.Pet',
                verbose_name='pets',
            ),
        ),
    ]
