# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-18 19:00
from __future__ import unicode_literals

from django.db import migrations
import filtered_many_to_many.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filtered_many_to_many', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pets',
            field=filtered_many_to_many.fields.FilteredManyToManyField(
                filter={'is_deleted': False},
                related_name='people',
                through='filtered_many_to_many.PersonPets',
                to='filtered_many_to_many.Pet',
                verbose_name='pets',
            ),
        ),
    ]
