# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-19 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import migrate_sql.operations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filtered_many_to_many', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPetsNonDeletedView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='pets',
            field=models.ManyToManyField(related_name='people', through='filtered_many_to_many.PersonPetsNonDeletedView', to='filtered_many_to_many.Pet', verbose_name='pets'),
        ),
        migrate_sql.operations.CreateSQL(
            name='make_filtered_many_to_many_personpetsnondeletedview',
            sql=[('CREATE VIEW filtered_many_to_many_personpetsnondeletedview AS SELECT "filtered_many_to_many_personpets"."id", "filtered_many_to_many_personpets"."person_id", "filtered_many_to_many_personpets"."pet_id", "filtered_many_to_many_personpets"."is_deleted" FROM "filtered_many_to_many_personpets" WHERE "filtered_many_to_many_personpets"."is_deleted" = %s;', (False,))],
            reverse_sql=[('DROP VIEW IF EXISTS filtered_many_to_many_personpetsnondeletedview;', None)],
        ),
    ]
